-- Seed data for Striver's A-Z DSA Sheet.
-- This file populates only shared catalog tables: sheets, topics, questions.
-- It is safe to run more than once.

begin;

insert into public.sheets (name, description)
select
  'Striver A-Z',
  'Striver''s A to Z DSA Sheet: a structured roadmap from DSA basics to advanced topics.'
where not exists (
  select 1 from public.sheets where name = 'Striver A-Z'
);

with target_sheet as (
  select id
  from public.sheets
  where name = 'Striver A-Z'
  order by created_at
  limit 1
),
topic_seed (name, order_index) as (
  values
    ('Step 1: Learn the Basics (Patterns, Recursion, Hashing)', 1),
    ('Step 2: Sorting Techniques', 2),
    ('Step 3: Arrays (Easy, Medium, Hard)', 3),
    ('Step 4: Binary Search', 4),
    ('Step 5: Strings', 5),
    ('Step 6: Linked Lists', 6),
    ('Step 7: Recursion & Backtracking', 7),
    ('Step 8: Bit Manipulation', 8),
    ('Step 9: Stack & Queues', 9),
    ('Step 10: Sliding Window', 10),
    ('Step 11: Heaps', 11),
    ('Step 12: Greedy', 12),
    ('Step 13: Binary Trees', 13),
    ('Step 14: Binary Search Trees', 14),
    ('Step 15: Graphs', 15),
    ('Step 16: Dynamic Programming', 16),
    ('Step 17: Tries', 17)
)
insert into public.topics (sheet_id, name, order_index)
select target_sheet.id, topic_seed.name, topic_seed.order_index
from target_sheet
cross join topic_seed
on conflict (sheet_id, order_index) do update
set name = excluded.name;

with target_sheet as (
  select id
  from public.sheets
  where name = 'Striver A-Z'
  order by created_at
  limit 1
),
question_seed (topic_order, title, difficulty, leetcode_url, order_index) as (
  values
    (1, 'Patterns', 'easy', null, 1),
    (1, 'Count Digits', 'easy', null, 2),
    (1, 'Reverse a Number', 'easy', 'https://leetcode.com/problems/reverse-integer/', 3),
    (1, 'Check Palindrome', 'easy', 'https://leetcode.com/problems/palindrome-number/', 4),
    (1, 'GCD Or HCF', 'easy', null, 5),
    (1, 'Armstrong Numbers', 'easy', null, 6),
    (1, 'Print all Divisors', 'easy', null, 7),
    (1, 'Check for Prime', 'easy', null, 8),
    (1, 'Sum of first N numbers', 'easy', null, 9),
    (1, 'Factorial of N numbers', 'easy', null, 10),
    (1, 'Reverse an array', 'easy', null, 11),
    (1, 'Check if a string is palindrome or not', 'easy', null, 12),
    (1, 'Fibonacci Number', 'easy', 'https://leetcode.com/problems/fibonacci-number/', 13),
    (1, 'Hashing Theory', 'easy', null, 14),
    (1, 'Counting frequencies of array elements', 'easy', null, 15),
    (1, 'Find the highest/lowest frequency element', 'easy', null, 16),

    (2, 'Selection Sort', 'easy', null, 1),
    (2, 'Bubble Sort', 'easy', null, 2),
    (2, 'Insertion Sort', 'easy', null, 3),
    (2, 'Merge Sort', 'medium', null, 4),
    (2, 'Recursive Bubble Sort', 'easy', null, 5),
    (2, 'Recursive Insertion Sort', 'easy', null, 6),
    (2, 'Quick Sort', 'medium', null, 7),

    (3, 'Largest Element in an Array', 'easy', null, 1),
    (3, 'Second Largest Element in an Array without sorting', 'easy', null, 2),
    (3, 'Check if the array is sorted', 'easy', null, 3),
    (3, 'Remove duplicates from Sorted array', 'easy', 'https://leetcode.com/problems/remove-duplicates-from-sorted-array/', 4),
    (3, 'Left Rotate an array by one place', 'easy', null, 5),
    (3, 'Left rotate an array by D places', 'medium', 'https://leetcode.com/problems/rotate-array/', 6),
    (3, 'Move Zeros to end', 'easy', 'https://leetcode.com/problems/move-zeroes/', 7),
    (3, 'Linear Search', 'easy', null, 8),
    (3, 'Find the Union', 'easy', null, 9),
    (3, 'Find missing number in an array', 'easy', 'https://leetcode.com/problems/missing-number/', 10),
    (3, 'Maximum Consecutive Ones', 'easy', 'https://leetcode.com/problems/max-consecutive-ones/', 11),
    (3, 'Find the number that appears once, and other numbers twice', 'easy', 'https://leetcode.com/problems/single-number/', 12),
    (3, 'Longest subarray with given sum K (positives)', 'easy', null, 13),
    (3, 'Longest subarray with sum K (Positives + Negatives)', 'medium', null, 14),
    (3, '2Sum Problem', 'easy', 'https://leetcode.com/problems/two-sum/', 15),
    (3, 'Sort an array of 0''s 1''s and 2''s', 'medium', 'https://leetcode.com/problems/sort-colors/', 16),
    (3, 'Majority Element (>n/2 times)', 'easy', 'https://leetcode.com/problems/majority-element/', 17),
    (3, 'Kadane''s Algorithm, maximum subarray sum', 'medium', 'https://leetcode.com/problems/maximum-subarray/', 18),
    (3, 'Stock Buy and Sell', 'easy', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 19),
    (3, 'Rearrange the array in alternating positive and negative items', 'medium', 'https://leetcode.com/problems/rearrange-array-elements-by-sign/', 20),
    (3, 'Next Permutation', 'medium', 'https://leetcode.com/problems/next-permutation/', 21),
    (3, 'Leaders in an Array problem', 'easy', null, 22),
    (3, 'Longest Consecutive Sequence in an Array', 'medium', 'https://leetcode.com/problems/longest-consecutive-sequence/', 23),
    (3, 'Set Matrix Zeros', 'medium', 'https://leetcode.com/problems/set-matrix-zeroes/', 24),
    (3, 'Rotate Matrix by 90 degrees', 'medium', 'https://leetcode.com/problems/rotate-image/', 25),
    (3, 'Print the matrix in spiral manner', 'medium', 'https://leetcode.com/problems/spiral-matrix/', 26),
    (3, 'Count subarrays with given sum', 'medium', 'https://leetcode.com/problems/subarray-sum-equals-k/', 27),
    (3, 'Pascal''s Triangle', 'easy', 'https://leetcode.com/problems/pascals-triangle/', 28),
    (3, 'Majority Element (n/3 times)', 'medium', 'https://leetcode.com/problems/majority-element-ii/', 29),
    (3, '3-Sum Problem', 'medium', 'https://leetcode.com/problems/3sum/', 30),
    (3, '4-Sum Problem', 'medium', 'https://leetcode.com/problems/4sum/', 31),
    (3, 'Largest Subarray with 0 Sum', 'medium', null, 32),
    (3, 'Count number of subarrays with given xor K', 'hard', null, 33),
    (3, 'Merge Overlapping Subintervals', 'medium', 'https://leetcode.com/problems/merge-intervals/', 34),
    (3, 'Merge two sorted arrays without extra space', 'easy', 'https://leetcode.com/problems/merge-sorted-array/', 35),
    (3, 'Find the repeating and missing number', 'hard', null, 36),
    (3, 'Count Inversions', 'hard', null, 37),
    (3, 'Reverse Pairs', 'hard', 'https://leetcode.com/problems/reverse-pairs/', 38),
    (3, 'Maximum Product Subarray', 'medium', 'https://leetcode.com/problems/maximum-product-subarray/', 39),

    (4, 'Binary Search to find X in sorted array', 'easy', 'https://leetcode.com/problems/binary-search/', 1),
    (4, 'Implement Lower Bound', 'easy', null, 2),
    (4, 'Implement Upper Bound', 'easy', null, 3),
    (4, 'Search Insert Position', 'easy', 'https://leetcode.com/problems/search-insert-position/', 4),
    (4, 'Floor/Ceil in Sorted Array', 'medium', null, 5),
    (4, 'First and Last Occurrences', 'medium', 'https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/', 6),
    (4, 'Count occurrences in sorted array', 'medium', null, 7),
    (4, 'Search in Rotated Sorted Array I', 'medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array/', 8),
    (4, 'Search in Rotated Sorted Array II', 'medium', 'https://leetcode.com/problems/search-in-rotated-sorted-array-ii/', 9),
    (4, 'Find minimum in Rotated Sorted Array', 'medium', 'https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/', 10),
    (4, 'Number of times array is rotated', 'medium', null, 11),
    (4, 'Single element in Sorted Array', 'medium', 'https://leetcode.com/problems/single-element-in-a-sorted-array/', 12),
    (4, 'Find peak element', 'medium', 'https://leetcode.com/problems/find-peak-element/', 13),
    (4, 'Square Root using Binary Search', 'easy', 'https://leetcode.com/problems/sqrtx/', 14),
    (4, 'Find Nth Root', 'medium', null, 15),
    (4, 'Koko Eating Bananas', 'medium', 'https://leetcode.com/problems/koko-eating-bananas/', 16),
    (4, 'Minimum days to make M bouquets', 'medium', 'https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/', 17),
    (4, 'Smallest Divisor', 'medium', 'https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/', 18),
    (4, 'Capacity To Ship Packages', 'medium', 'https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/', 19),
    (4, 'Kth Missing Positive Number', 'easy', 'https://leetcode.com/problems/kth-missing-positive-number/', 20),
    (4, 'Aggressive Cows', 'hard', null, 21),
    (4, 'Book Allocation Problem', 'hard', null, 22),
    (4, 'Split Array - Largest Sum', 'hard', 'https://leetcode.com/problems/split-array-largest-sum/', 23),
    (4, 'Painter''s Partition', 'hard', null, 24),
    (4, 'Minimize Max Distance to Gas Station', 'hard', 'https://leetcode.com/problems/minimize-max-distance-to-gas-station/', 25),
    (4, 'Median of 2 sorted arrays', 'hard', 'https://leetcode.com/problems/median-of-two-sorted-arrays/', 26),
    (4, 'Kth element of 2 sorted arrays', 'hard', null, 27),
    (4, 'Row with maximum number of 1''s', 'medium', null, 28),
    (4, 'Search in a 2D matrix', 'medium', 'https://leetcode.com/problems/search-a-2d-matrix/', 29),
    (4, 'Search in row-column sorted matrix', 'medium', 'https://leetcode.com/problems/search-a-2d-matrix-ii/', 30),
    (4, 'Find Peak Element (2D)', 'medium', 'https://leetcode.com/problems/find-a-peak-element-ii/', 31),
    (4, 'Matrix Median', 'hard', null, 32),

    (5, 'Remove Outermost Parenthesis', 'easy', 'https://leetcode.com/problems/remove-outermost-parentheses/', 1),
    (5, 'Reverse Words in a String', 'medium', 'https://leetcode.com/problems/reverse-words-in-a-string/', 2),
    (5, 'Largest Odd Number in String', 'easy', 'https://leetcode.com/problems/largest-odd-number-in-string/', 3),
    (5, 'Longest Common Prefix', 'easy', 'https://leetcode.com/problems/longest-common-prefix/', 4),
    (5, 'Isomorphic Strings', 'easy', 'https://leetcode.com/problems/isomorphic-strings/', 5),
    (5, 'Check for Rotation', 'easy', 'https://leetcode.com/problems/rotate-string/', 6),
    (5, 'Check for Anagram', 'easy', 'https://leetcode.com/problems/valid-anagram/', 7),
    (5, 'Sort Characters by Frequency', 'medium', 'https://leetcode.com/problems/sort-characters-by-frequency/', 8),
    (5, 'Maximum Nesting Depth of the Parentheses', 'easy', 'https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/', 9),
    (5, 'Roman Number Conversions', 'easy', 'https://leetcode.com/problems/roman-to-integer/', 10),
    (5, 'Implement Atoi', 'medium', 'https://leetcode.com/problems/string-to-integer-atoi/', 11),
    (5, 'Count Number of Substrings', 'medium', 'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/', 12),
    (5, 'Longest Palindromic Substring', 'medium', 'https://leetcode.com/problems/longest-palindromic-substring/', 13),
    (5, 'Sum of Beauty of Substrings', 'medium', 'https://leetcode.com/problems/sum-of-beauty-of-all-substrings/', 14),
    (5, 'Reverse Words in String', 'medium', 'https://leetcode.com/problems/reverse-words-in-a-string/', 15),

    (6, 'Introduction to LinkedList', 'easy', null, 1),
    (6, 'Inserting a node in LinkedList', 'easy', null, 2),
    (6, 'Deleting a node in LinkedList', 'easy', null, 3),
    (6, 'Find the length of the linkedlist', 'easy', null, 4),
    (6, 'Search an element in the LL', 'easy', null, 5),
    (6, 'Introduction to DLL', 'easy', null, 6),
    (6, 'Reverse a DLL', 'medium', null, 7),
    (6, 'Middle of a LinkedList', 'easy', 'https://leetcode.com/problems/middle-of-the-linked-list/', 8),
    (6, 'Reverse a LinkedList', 'easy', 'https://leetcode.com/problems/reverse-linked-list/', 9),
    (6, 'Detect a loop in LL', 'easy', 'https://leetcode.com/problems/linked-list-cycle/', 10),
    (6, 'Find the starting point in LL', 'medium', 'https://leetcode.com/problems/linked-list-cycle-ii/', 11),
    (6, 'Length of Loop in LL', 'medium', null, 12),
    (6, 'Check if LL is palindrome or not', 'easy', 'https://leetcode.com/problems/palindrome-linked-list/', 13),
    (6, 'Segregate odd and even nodes in LL', 'medium', 'https://leetcode.com/problems/odd-even-linked-list/', 14),
    (6, 'Remove Nth node from the back of the LL', 'medium', 'https://leetcode.com/problems/remove-nth-node-from-end-of-list/', 15),
    (6, 'Delete the middle node of LL', 'medium', 'https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/', 16),
    (6, 'Sort LL', 'medium', 'https://leetcode.com/problems/sort-list/', 17),
    (6, 'Find the intersection point of Y LL', 'easy', 'https://leetcode.com/problems/intersection-of-two-linked-lists/', 18),
    (6, 'Add 1 to a number represented by LL', 'medium', null, 19),
    (6, 'Add 2 numbers in LL', 'medium', 'https://leetcode.com/problems/add-two-numbers/', 20),
    (6, 'Delete all occurrences of a key in DLL', 'medium', null, 21),
    (6, 'Find pairs with given sum in DLL', 'medium', null, 22),
    (6, 'Remove duplicates from sorted DLL', 'medium', null, 23),
    (6, 'Reverse LL in group of given size K', 'hard', 'https://leetcode.com/problems/reverse-nodes-in-k-group/', 24),
    (6, 'Rotate a LL', 'medium', 'https://leetcode.com/problems/rotate-list/', 25),
    (6, 'Flattening of LL', 'hard', 'https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/', 26),
    (6, 'Clone a Linked List with random and next pointer', 'medium', 'https://leetcode.com/problems/copy-list-with-random-pointer/', 27),

    (7, 'Recursive Implementation of atoi()', 'medium', 'https://leetcode.com/problems/string-to-integer-atoi/', 1),
    (7, 'Pow(x, n)', 'medium', 'https://leetcode.com/problems/powx-n/', 2),
    (7, 'Count Good numbers', 'medium', 'https://leetcode.com/problems/count-good-numbers/', 3),
    (7, 'Sort a stack using recursion', 'medium', null, 4),
    (7, 'Reverse a stack using recursion', 'medium', null, 5),
    (7, 'Generate all binary strings', 'medium', null, 6),
    (7, 'Generate Parentheses', 'medium', 'https://leetcode.com/problems/generate-parentheses/', 7),
    (7, 'Print all subsequences / Power Set', 'medium', 'https://leetcode.com/problems/subsets/', 8),
    (7, 'Count all subsequences with sum K', 'medium', null, 9),
    (7, 'Combination Sum', 'medium', 'https://leetcode.com/problems/combination-sum/', 10),
    (7, 'Combination Sum II', 'medium', 'https://leetcode.com/problems/combination-sum-ii/', 11),
    (7, 'Subset Sum I', 'medium', null, 12),
    (7, 'Subset Sum II', 'medium', 'https://leetcode.com/problems/subsets-ii/', 13),
    (7, 'Combination Sum III', 'medium', 'https://leetcode.com/problems/combination-sum-iii/', 14),
    (7, 'Letter Combinations of a Phone Number', 'medium', 'https://leetcode.com/problems/letter-combinations-of-a-phone-number/', 15),
    (7, 'Palindrome Partitioning', 'medium', 'https://leetcode.com/problems/palindrome-partitioning/', 16),
    (7, 'Word Search', 'medium', 'https://leetcode.com/problems/word-search/', 17),
    (7, 'N Queen', 'hard', 'https://leetcode.com/problems/n-queens/', 18),
    (7, 'Rat in a Maze', 'hard', null, 19),
    (7, 'Word Break', 'medium', 'https://leetcode.com/problems/word-break/', 20),
    (7, 'M Coloring', 'hard', null, 21),
    (7, 'Sudoku Solver', 'hard', 'https://leetcode.com/problems/sudoku-solver/', 22),
    (7, 'Expression Add Operators', 'hard', 'https://leetcode.com/problems/expression-add-operators/', 23),

    (8, 'Introduction to Bits', 'easy', null, 1),
    (8, 'Check i-th bit', 'easy', null, 2),
    (8, 'Check odd/even', 'easy', null, 3),
    (8, 'Check power of 2', 'easy', 'https://leetcode.com/problems/power-of-two/', 4),
    (8, 'Count set bits', 'easy', 'https://leetcode.com/problems/number-of-1-bits/', 5),
    (8, 'Set/Unset rightmost bit', 'easy', null, 6),
    (8, 'Swap numbers', 'easy', null, 7),
    (8, 'Divide integers', 'medium', 'https://leetcode.com/problems/divide-two-integers/', 8),
    (8, 'Count bits to be flipped', 'easy', 'https://leetcode.com/problems/minimum-bit-flips-to-convert-number/', 9),
    (8, 'Find odd occurring number', 'easy', 'https://leetcode.com/problems/single-number/', 10),
    (8, 'Power Set', 'medium', 'https://leetcode.com/problems/subsets/', 11),
    (8, 'XOR from L to R', 'medium', 'https://leetcode.com/problems/xor-queries-of-a-subarray/', 12),
    (8, 'Two numbers with odd occurrences', 'medium', 'https://leetcode.com/problems/single-number-iii/', 13),
    (8, 'Prime Factors', 'medium', null, 14),
    (8, 'All Divisors', 'easy', null, 15),
    (8, 'Sieve of Eratosthenes', 'medium', 'https://leetcode.com/problems/count-primes/', 16),
    (8, 'Prime Factorisation using Sieve', 'medium', null, 17),
    (8, 'Power(n, x)', 'medium', 'https://leetcode.com/problems/powx-n/', 18),

    (9, 'Implement Stack using Arrays', 'easy', null, 1),
    (9, 'Implement Queue using Arrays', 'easy', null, 2),
    (9, 'Implement Stack using Queue', 'easy', 'https://leetcode.com/problems/implement-stack-using-queues/', 3),
    (9, 'Implement Queue using Stack', 'easy', 'https://leetcode.com/problems/implement-queue-using-stacks/', 4),
    (9, 'Check Balanced Parentheses', 'easy', 'https://leetcode.com/problems/valid-parentheses/', 5),
    (9, 'Implement Min Stack', 'medium', 'https://leetcode.com/problems/min-stack/', 6),
    (9, 'Next Greater Element', 'easy', 'https://leetcode.com/problems/next-greater-element-i/', 7),
    (9, 'Next Greater Element II', 'medium', 'https://leetcode.com/problems/next-greater-element-ii/', 8),
    (9, 'Next Smaller Element', 'medium', null, 9),
    (9, 'Trapping Rainwater', 'hard', 'https://leetcode.com/problems/trapping-rain-water/', 10),
    (9, 'Sum of Subarray Minimum', 'medium', 'https://leetcode.com/problems/sum-of-subarray-minimums/', 11),
    (9, 'Asteroid Collision', 'medium', 'https://leetcode.com/problems/asteroid-collision/', 12),
    (9, 'Sum of Subarray Ranges', 'medium', 'https://leetcode.com/problems/sum-of-subarray-ranges/', 13),
    (9, 'Remove K Digits', 'medium', 'https://leetcode.com/problems/remove-k-digits/', 14),
    (9, 'Largest Rectangle in Histogram', 'hard', 'https://leetcode.com/problems/largest-rectangle-in-histogram/', 15),
    (9, 'Maximal Rectangles', 'hard', 'https://leetcode.com/problems/maximal-rectangle/', 16),
    (9, 'Sliding Window Maximum', 'hard', 'https://leetcode.com/problems/sliding-window-maximum/', 17),
    (9, 'Stock Span Problem', 'medium', 'https://leetcode.com/problems/online-stock-span/', 18),
    (9, 'Celebrity Problem', 'medium', null, 19),
    (9, 'LRU Cache', 'medium', 'https://leetcode.com/problems/lru-cache/', 20),
    (9, 'LFU Cache', 'hard', 'https://leetcode.com/problems/lfu-cache/', 21),

    (10, 'Longest Substring Without Repeating Characters', 'medium', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/', 1),
    (10, 'Max Consecutive Ones III', 'medium', 'https://leetcode.com/problems/max-consecutive-ones-iii/', 2),
    (10, 'Fruit Into Baskets', 'medium', 'https://leetcode.com/problems/fruit-into-baskets/', 3),
    (10, 'Longest Repeating Character Replacement', 'medium', 'https://leetcode.com/problems/longest-repeating-character-replacement/', 4),
    (10, 'Binary Subarray with Sum', 'medium', 'https://leetcode.com/problems/binary-subarrays-with-sum/', 5),
    (10, 'Count Nice Subarrays', 'medium', 'https://leetcode.com/problems/count-number-of-nice-subarrays/', 6),
    (10, 'Number of Substring Containing All Characters', 'medium', 'https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/', 7),
    (10, 'Maximum Points from Cards', 'medium', 'https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/', 8),
    (10, 'Longest Substring with K Distinct Characters', 'medium', 'https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/', 9),
    (10, 'Subarray with K Different Integers', 'hard', 'https://leetcode.com/problems/subarrays-with-k-different-integers/', 10),
    (10, 'Minimum Window Substring', 'hard', 'https://leetcode.com/problems/minimum-window-substring/', 11),
    (10, 'Minimum Window Subsequence', 'hard', 'https://leetcode.com/problems/minimum-window-subsequence/', 12),

    (11, 'Introduction to Priority Queues', 'easy', null, 1),
    (11, 'Min/Max Heap Implementation', 'medium', null, 2),
    (11, 'Check if Array is Min-Heap', 'easy', null, 3),
    (11, 'Convert Min to Max Heap', 'medium', null, 4),
    (11, 'Kth Largest Element', 'medium', 'https://leetcode.com/problems/kth-largest-element-in-an-array/', 5),
    (11, 'Kth Smallest Element', 'medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/', 6),
    (11, 'Sort K Sorted Array', 'medium', null, 7),
    (11, 'Merge M Sorted Lists', 'hard', 'https://leetcode.com/problems/merge-k-sorted-lists/', 8),
    (11, 'Replace Elements by Rank', 'easy', 'https://leetcode.com/problems/rank-transform-of-an-array/', 9),
    (11, 'Task Scheduler', 'medium', 'https://leetcode.com/problems/task-scheduler/', 10),
    (11, 'Hands of Straights', 'medium', 'https://leetcode.com/problems/hand-of-straights/', 11),
    (11, 'Design Twitter', 'medium', 'https://leetcode.com/problems/design-twitter/', 12),
    (11, 'Connect N Ropes', 'medium', null, 13),
    (11, 'Kth Largest in Stream', 'easy', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/', 14),
    (11, 'Maximum Sum Combination', 'medium', null, 15),
    (11, 'Find Median from Data Stream', 'hard', 'https://leetcode.com/problems/find-median-from-data-stream/', 16),
    (11, 'K Most Frequent Elements', 'medium', 'https://leetcode.com/problems/top-k-frequent-elements/', 17),

    (12, 'Assign Cookies', 'easy', 'https://leetcode.com/problems/assign-cookies/', 1),
    (12, 'Fractional Knapsack', 'medium', null, 2),
    (12, 'Minimum Coins', 'easy', null, 3),
    (12, 'Lemonade Change', 'easy', 'https://leetcode.com/problems/lemonade-change/', 4),
    (12, 'Valid Parenthesis', 'medium', 'https://leetcode.com/problems/valid-parenthesis-string/', 5),
    (12, 'N Meetings in One Room', 'medium', null, 6),
    (12, 'Jump Game', 'medium', 'https://leetcode.com/problems/jump-game/', 7),
    (12, 'Jump Game II', 'medium', 'https://leetcode.com/problems/jump-game-ii/', 8),
    (12, 'Minimum Platforms', 'medium', null, 9),
    (12, 'Job Sequencing', 'medium', null, 10),
    (12, 'Candy Distribution', 'hard', 'https://leetcode.com/problems/candy/', 11),
    (12, 'Shortest Job First', 'medium', null, 12),
    (12, 'LRU Page Replacement', 'medium', null, 13),
    (12, 'Insert Interval', 'medium', 'https://leetcode.com/problems/insert-interval/', 14),
    (12, 'Merge Intervals', 'medium', 'https://leetcode.com/problems/merge-intervals/', 15),
    (12, 'Non-overlapping Intervals', 'medium', 'https://leetcode.com/problems/non-overlapping-intervals/', 16),

    (13, 'Preorder Traversal', 'easy', 'https://leetcode.com/problems/binary-tree-preorder-traversal/', 1),
    (13, 'Inorder Traversal', 'easy', 'https://leetcode.com/problems/binary-tree-inorder-traversal/', 2),
    (13, 'Postorder Traversal', 'easy', 'https://leetcode.com/problems/binary-tree-postorder-traversal/', 3),
    (13, 'Level Order Traversal', 'medium', 'https://leetcode.com/problems/binary-tree-level-order-traversal/', 4),
    (13, 'Height of Binary Tree', 'easy', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/', 5),
    (13, 'Check Balanced Tree', 'easy', 'https://leetcode.com/problems/balanced-binary-tree/', 6),
    (13, 'Diameter of Tree', 'easy', 'https://leetcode.com/problems/diameter-of-binary-tree/', 7),
    (13, 'Maximum Path Sum', 'hard', 'https://leetcode.com/problems/binary-tree-maximum-path-sum/', 8),
    (13, 'Check Identical Trees', 'easy', 'https://leetcode.com/problems/same-tree/', 9),
    (13, 'Zigzag Traversal', 'medium', 'https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/', 10),
    (13, 'Boundary Traversal', 'medium', null, 11),
    (13, 'Vertical Order Traversal', 'hard', 'https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/', 12),
    (13, 'Top View', 'medium', null, 13),
    (13, 'Bottom View', 'medium', null, 14),
    (13, 'Right/Left View', 'medium', 'https://leetcode.com/problems/binary-tree-right-side-view/', 15),
    (13, 'Symmetric Tree', 'easy', 'https://leetcode.com/problems/symmetric-tree/', 16),
    (13, 'Root to Node Path', 'medium', null, 17),
    (13, 'LCA in Binary Tree', 'medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/', 18),
    (13, 'Maximum Width', 'medium', 'https://leetcode.com/problems/maximum-width-of-binary-tree/', 19),
    (13, 'Children Sum Property', 'medium', null, 20),
    (13, 'Nodes at Distance K', 'medium', 'https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/', 21),
    (13, 'Burn Binary Tree', 'hard', null, 22),
    (13, 'Count Total Nodes', 'easy', 'https://leetcode.com/problems/count-complete-tree-nodes/', 23),
    (13, 'Construct from Inorder/Preorder', 'medium', 'https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/', 24),
    (13, 'Construct from Postorder/Inorder', 'medium', 'https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/', 25),
    (13, 'Serialize and Deserialize', 'hard', 'https://leetcode.com/problems/serialize-and-deserialize-binary-tree/', 26),
    (13, 'Morris Preorder', 'medium', null, 27),
    (13, 'Morris Inorder', 'medium', null, 28),
    (13, 'Flatten to LinkedList', 'medium', 'https://leetcode.com/problems/flatten-binary-tree-to-linked-list/', 29),

    (14, 'Introduction to BST', 'easy', null, 1),
    (14, 'Search in BST', 'easy', 'https://leetcode.com/problems/search-in-a-binary-search-tree/', 2),
    (14, 'Find Min/Max in BST', 'easy', null, 3),
    (14, 'Ceil in BST', 'easy', null, 4),
    (14, 'Floor in BST', 'easy', null, 5),
    (14, 'Insert Node in BST', 'medium', 'https://leetcode.com/problems/insert-into-a-binary-search-tree/', 6),
    (14, 'Delete Node in BST', 'medium', 'https://leetcode.com/problems/delete-node-in-a-bst/', 7),
    (14, 'K-th Smallest/Largest in BST', 'medium', 'https://leetcode.com/problems/kth-smallest-element-in-a-bst/', 8),
    (14, 'Check if Tree is BST', 'medium', 'https://leetcode.com/problems/validate-binary-search-tree/', 9),
    (14, 'LCA in BST', 'medium', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/', 10),
    (14, 'Construct BST from Preorder', 'medium', 'https://leetcode.com/problems/construct-binary-search-tree-from-preorder-traversal/', 11),
    (14, 'Inorder Successor/Predecessor', 'medium', null, 12),
    (14, 'Merge 2 BSTs', 'medium', null, 13),
    (14, 'Two Sum in BST', 'easy', 'https://leetcode.com/problems/two-sum-iv-input-is-a-bst/', 14),
    (14, 'Recover BST', 'medium', 'https://leetcode.com/problems/recover-binary-search-tree/', 15),
    (14, 'Largest BST in Binary Tree', 'hard', null, 16),

    (15, 'BFS', 'easy', null, 1),
    (15, 'DFS', 'easy', null, 2),
    (15, 'Number of Provinces', 'medium', 'https://leetcode.com/problems/number-of-provinces/', 3),
    (15, 'Rotten Oranges', 'medium', 'https://leetcode.com/problems/rotting-oranges/', 4),
    (15, 'Flood Fill', 'easy', 'https://leetcode.com/problems/flood-fill/', 5),
    (15, 'Cycle Detection (BFS)', 'medium', null, 6),
    (15, 'Cycle Detection (DFS)', 'medium', null, 7),
    (15, '0/1 Matrix', 'medium', 'https://leetcode.com/problems/01-matrix/', 8),
    (15, 'Surrounded Regions', 'medium', 'https://leetcode.com/problems/surrounded-regions/', 9),
    (15, 'Number of Enclaves', 'medium', 'https://leetcode.com/problems/number-of-enclaves/', 10),
    (15, 'Word Ladder I', 'hard', 'https://leetcode.com/problems/word-ladder/', 11),
    (15, 'Word Ladder II', 'hard', 'https://leetcode.com/problems/word-ladder-ii/', 12),
    (15, 'Number of Distinct Islands', 'medium', null, 13),
    (15, 'Bipartite Graph', 'medium', 'https://leetcode.com/problems/is-graph-bipartite/', 14),
    (15, 'Cycle Detection in Directed Graph', 'medium', null, 15),
    (15, 'Topological Sort', 'medium', null, 16),
    (15, 'Kahn''s Algorithm', 'medium', null, 17),
    (15, 'Course Schedule I', 'medium', 'https://leetcode.com/problems/course-schedule/', 18),
    (15, 'Course Schedule II', 'medium', 'https://leetcode.com/problems/course-schedule-ii/', 19),
    (15, 'Find Eventual Safe States', 'medium', 'https://leetcode.com/problems/find-eventual-safe-states/', 20),
    (15, 'Alien Dictionary', 'hard', null, 21),
    (15, 'Shortest Path in Unweighted Graph', 'medium', null, 22),
    (15, 'Shortest Path in DAG', 'medium', null, 23),
    (15, 'Dijkstra''s Algorithm', 'medium', null, 24),
    (15, 'Shortest Path in Binary Maze', 'medium', 'https://leetcode.com/problems/shortest-path-in-binary-matrix/', 25),
    (15, 'Path with Minimum Effort', 'medium', 'https://leetcode.com/problems/path-with-minimum-effort/', 26),
    (15, 'Cheapest Flights within K Stops', 'medium', 'https://leetcode.com/problems/cheapest-flights-within-k-stops/', 27),
    (15, 'Network Delay Time', 'medium', 'https://leetcode.com/problems/network-delay-time/', 28),
    (15, 'Number of Ways to Destination', 'medium', 'https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/', 29),
    (15, 'Bellman Ford Algorithm', 'medium', null, 30),
    (15, 'Floyd Warshall Algorithm', 'medium', null, 31),
    (15, 'City With Smallest Neighbors', 'medium', 'https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/', 32),
    (15, 'Minimum Spanning Tree', 'medium', null, 33),
    (15, 'Prim''s Algorithm', 'medium', null, 34),
    (15, 'Disjoint Set', 'medium', null, 35),
    (15, 'Kruskal''s Algorithm', 'medium', null, 36),
    (15, 'Number of Operations for Network', 'medium', 'https://leetcode.com/problems/number-of-operations-to-make-network-connected/', 37),
    (15, 'Most Stones Removed', 'medium', 'https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/', 38),
    (15, 'Accounts Merge', 'medium', 'https://leetcode.com/problems/accounts-merge/', 39),
    (15, 'Making Large Island', 'hard', 'https://leetcode.com/problems/making-a-large-island/', 40),
    (15, 'Swim in Rising Water', 'hard', 'https://leetcode.com/problems/swim-in-rising-water/', 41),
    (15, 'Bridges in Graph', 'hard', 'https://leetcode.com/problems/critical-connections-in-a-network/', 42),
    (15, 'Articulation Point', 'hard', null, 43),
    (15, 'Kosaraju''s Algorithm', 'hard', null, 44),

    (16, 'Dynamic Programming Introduction', 'easy', null, 1),
    (16, 'Climbing Stairs', 'easy', 'https://leetcode.com/problems/climbing-stairs/', 2),
    (16, 'Frog Jump', 'medium', null, 3),
    (16, 'Frog Jump with K Distance', 'medium', null, 4),
    (16, 'Maximum Sum of Non-Adjacent Elements', 'medium', null, 5),
    (16, 'House Robber', 'medium', 'https://leetcode.com/problems/house-robber/', 6),
    (16, 'Ninja''s Training', 'medium', null, 7),
    (16, 'Grid Unique Paths', 'medium', 'https://leetcode.com/problems/unique-paths/', 8),
    (16, 'Grid Unique Paths 2', 'medium', 'https://leetcode.com/problems/unique-paths-ii/', 9),
    (16, 'Minimum Path Sum in Grid', 'medium', 'https://leetcode.com/problems/minimum-path-sum/', 10),
    (16, 'Minimum Path Sum in Triangle', 'medium', 'https://leetcode.com/problems/triangle/', 11),
    (16, 'Maximum Falling Path Sum', 'medium', 'https://leetcode.com/problems/minimum-falling-path-sum/', 12),
    (16, '3D DP - Ninja and Friends', 'hard', null, 13),
    (16, 'Subset Sum Equal to Target', 'medium', null, 14),
    (16, 'Partition Equal Subset Sum', 'medium', 'https://leetcode.com/problems/partition-equal-subset-sum/', 15),
    (16, 'Count Subsets with Sum K', 'medium', null, 16),
    (16, 'Minimum Coins', 'medium', 'https://leetcode.com/problems/coin-change/', 17),
    (16, 'Target Sum', 'medium', 'https://leetcode.com/problems/target-sum/', 18),
    (16, 'Coin Change 2', 'medium', 'https://leetcode.com/problems/coin-change-ii/', 19),
    (16, 'Unbounded Knapsack', 'medium', null, 20),
    (16, 'Rod Cutting Problem', 'medium', null, 21),
    (16, 'Longest Common Subsequence', 'medium', 'https://leetcode.com/problems/longest-common-subsequence/', 22),
    (16, 'Print LCS', 'medium', null, 23),
    (16, 'Longest Common Substring', 'medium', null, 24),
    (16, 'Longest Palindromic Subsequence', 'medium', 'https://leetcode.com/problems/longest-palindromic-subsequence/', 25),
    (16, 'Minimum Insertions for Palindrome', 'hard', 'https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/', 26),
    (16, 'Shortest Common Supersequence', 'hard', 'https://leetcode.com/problems/shortest-common-supersequence/', 27),
    (16, 'Distinct Subsequences', 'hard', 'https://leetcode.com/problems/distinct-subsequences/', 28),
    (16, 'Edit Distance', 'medium', 'https://leetcode.com/problems/edit-distance/', 29),
    (16, 'Wildcard Matching', 'hard', 'https://leetcode.com/problems/wildcard-matching/', 30),
    (16, 'Best Time to Buy and Sell Stock', 'easy', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/', 31),
    (16, 'Buy and Sell Stock II', 'medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/', 32),
    (16, 'Buy and Sell Stock III', 'hard', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/', 33),
    (16, 'Buy and Sell Stock IV', 'hard', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/', 34),
    (16, 'Buy and Sell with Cooldown', 'medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/', 35),
    (16, 'Buy and Sell with Transaction Fee', 'medium', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/', 36),
    (16, 'Longest Increasing Subsequence', 'medium', 'https://leetcode.com/problems/longest-increasing-subsequence/', 37),
    (16, 'Largest Divisible Subset', 'medium', 'https://leetcode.com/problems/largest-divisible-subset/', 38),
    (16, 'Longest String Chain', 'medium', 'https://leetcode.com/problems/longest-string-chain/', 39),
    (16, 'Number of LIS', 'medium', 'https://leetcode.com/problems/number-of-longest-increasing-subsequence/', 40),
    (16, 'Matrix Chain Multiplication', 'hard', null, 41),
    (16, 'Minimum Cost to Cut Stick', 'hard', 'https://leetcode.com/problems/minimum-cost-to-cut-a-stick/', 42),
    (16, 'Burst Balloons', 'hard', 'https://leetcode.com/problems/burst-balloons/', 43),
    (16, 'Evaluate Boolean Expression', 'hard', null, 44),
    (16, 'Palindrome Partitioning II', 'hard', 'https://leetcode.com/problems/palindrome-partitioning-ii/', 45),
    (16, 'Partition Array for Maximum Sum', 'medium', 'https://leetcode.com/problems/partition-array-for-maximum-sum/', 46),
    (16, 'Maximum Rectangle Area', 'hard', 'https://leetcode.com/problems/maximal-rectangle/', 47),
    (16, 'Count Square Submatrices', 'medium', 'https://leetcode.com/problems/count-square-submatrices-with-all-ones/', 48),

    (17, 'Implement TRIE', 'medium', 'https://leetcode.com/problems/implement-trie-prefix-tree/', 1),
    (17, 'Implement Trie II', 'medium', 'https://leetcode.com/problems/implement-trie-ii-prefix-tree/', 2),
    (17, 'Longest String with All Prefixes', 'easy', 'https://leetcode.com/problems/longest-word-in-dictionary/', 3),
    (17, 'Number of Distinct Substrings', 'medium', null, 4),
    (17, 'Bit Prerequisites', 'easy', null, 5),
    (17, 'Maximum XOR of Two Numbers', 'medium', 'https://leetcode.com/problems/maximum-xor-of-two-numbers-in-an-array/', 6),
    (17, 'Maximum XOR With Element', 'hard', 'https://leetcode.com/problems/maximum-xor-with-an-element-from-array/', 7)
)
insert into public.questions (topic_id, title, difficulty, leetcode_url, order_index)
select
  topics.id,
  question_seed.title,
  question_seed.difficulty,
  question_seed.leetcode_url,
  question_seed.order_index
from question_seed
join target_sheet on true
join public.topics
  on topics.sheet_id = target_sheet.id
 and topics.order_index = question_seed.topic_order
on conflict (topic_id, order_index) do update
set
  title = excluded.title,
  difficulty = excluded.difficulty,
  leetcode_url = excluded.leetcode_url;

commit;
